### PR TITLE
Add face orientation to driver video

### PR DESCRIPTION
**Pull request by chrisinajar**
I think we need to push a new version of log reader and bump the version here before this will work.

It draws a simple circle and a line coming from the center of the circle. The circle gets slightly larger and slightly less opaque when the confidence is low, however this particular model is most of the time positive or clueless so it mostly just appears and disappears when prob drops below 80%

here's how it looks currently:

image

image

### CODE REVIEW

**Comment by ZwX1616** [comment]
looks great! can we also overlay the probability numbers on the picture?
e.g:

**Comment by geohot** [comment]
The numbers themselves might be a bit much, but fades based on probs are nice. Can we add the eyes too?

**Comment by chrisinajar** [comment]
I think the only eye data i have is the probability each given eye is shut, i can always display that with a circle in hardcoded offsets from the nose

**Comment by ZwX1616** [comment]
> The numbers themselves might be a bit much, but fades based on probs are nice. Can we add the eyes too?

the eye positions are outputed by the model but not written to the log in current version

**Comment by chrisinajar** [comment]
Made the black nose circle either red or green based on if the driver is distracted or not

**Pull request merged**
